window.QUESTIONS = [
  {
    "id": "Paper 1-24",
    "paper": "Paper 1",
    "questionNumber": 24,
    "page": 11,
    "image": "gl-pages/page-011.jpg",
    "world": "🏙 Neon City",
    "answer": "30",
    "rarity": "common"
  },
  {
    "id": "Paper 1-32",
    "paper": "Paper 1",
    "questionNumber": 32,
    "page": 13,
    "image": "gl-pages/page-013.jpg",
    "world": "🏙 Neon City",
    "answer": "E",
    "rarity": "common"
  },
  {
    "id": "Paper 1-33",
    "paper": "Paper 1",
    "questionNumber": 33,
    "page": 14,
    "image": "gl-pages/page-014.jpg",
    "world": "🏙 Neon City",
    "answer": "25%",
    "rarity": "common"
  },
  {
    "id": "Paper 1-36",
    "paper": "Paper 1",
    "questionNumber": 36,
    "page": 15,
    "image": "gl-pages/page-015.jpg",
    "world": "🏙 Neon City",
    "answer": "40%",
    "rarity": "rare"
  },
  {
    "id": "Paper 1-39",
    "paper": "Paper 1",
    "questionNumber": 39,
    "page": 16,
    "image": "gl-pages/page-016.jpg",
    "world": "🏙 Neon City",
    "answer": "16 m²",
    "rarity": "rare"
  },
  {
    "id": "Paper 1-41",
    "paper": "Paper 1",
    "questionNumber": 41,
    "page": 17,
    "image": "gl-pages/page-017.jpg",
    "world": "🏙 Neon City",
    "answer": "16 cm³",
    "rarity": "rare"
  },
  {
    "id": "Paper 1-43",
    "paper": "Paper 1",
    "questionNumber": 43,
    "page": 18,
    "image": "gl-pages/page-018.jpg",
    "world": "🏙 Neon City",
    "answer": "0.98",
    "rarity": "rare"
  },
  {
    "id": "Paper 1-44",
    "paper": "Paper 1",
    "questionNumber": 44,
    "page": 18,
    "image": "gl-pages/page-018.jpg",
    "world": "🏙 Neon City",
    "answer": "A",
    "rarity": "rare"
  },
  {
    "id": "Paper 1-46",
    "paper": "Paper 1",
    "questionNumber": 46,
    "page": 19,
    "image": "gl-pages/page-019.jpg",
    "world": "🏙 Neon City",
    "answer": "78°",
    "rarity": "legendary"
  },
  {
    "id": "Paper 1-47",
    "paper": "Paper 1",
    "questionNumber": 47,
    "page": 19,
    "image": "gl-pages/page-019.jpg",
    "world": "🏙 Neon City",
    "answer": "10",
    "rarity": "legendary"
  },
  {
    "id": "Paper 1-48",
    "paper": "Paper 1",
    "questionNumber": 48,
    "page": 20,
    "image": "gl-pages/page-020.jpg",
    "world": "🏙 Neon City",
    "answer": "110°",
    "rarity": "legendary"
  },
  {
    "id": "Paper 1-50",
    "paper": "Paper 1",
    "questionNumber": 50,
    "page": 21,
    "image": "gl-pages/page-021.jpg",
    "world": "🏙 Neon City",
    "answer": "675 litres",
    "rarity": "legendary"
  },
  {
    "id": "Paper 2-21",
    "paper": "Paper 2",
    "questionNumber": 21,
    "page": 30,
    "image": "gl-pages/page-030.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "37 m",
    "rarity": "common"
  },
  {
    "id": "Paper 2-22",
    "paper": "Paper 2",
    "questionNumber": 22,
    "page": 30,
    "image": "gl-pages/page-030.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "A",
    "rarity": "common"
  },
  {
    "id": "Paper 2-26",
    "paper": "Paper 2",
    "questionNumber": 26,
    "page": 31,
    "image": "gl-pages/page-031.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "40%",
    "rarity": "common"
  },
  {
    "id": "Paper 2-27",
    "paper": "Paper 2",
    "questionNumber": 27,
    "page": 32,
    "image": "gl-pages/page-032.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "-3°C",
    "rarity": "common"
  },
  {
    "id": "Paper 2-31",
    "paper": "Paper 2",
    "questionNumber": 31,
    "page": 33,
    "image": "gl-pages/page-033.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "13.5 cm²",
    "rarity": "common"
  },
  {
    "id": "Paper 2-35",
    "paper": "Paper 2",
    "questionNumber": 35,
    "page": 35,
    "image": "gl-pages/page-035.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "3",
    "rarity": "rare"
  },
  {
    "id": "Paper 2-39",
    "paper": "Paper 2",
    "questionNumber": 39,
    "page": 37,
    "image": "gl-pages/page-037.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "E",
    "rarity": "rare"
  },
  {
    "id": "Paper 2-42",
    "paper": "Paper 2",
    "questionNumber": 42,
    "page": 39,
    "image": "gl-pages/page-039.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "D",
    "rarity": "rare"
  },
  {
    "id": "Paper 2-44",
    "paper": "Paper 2",
    "questionNumber": 44,
    "page": 39,
    "image": "gl-pages/page-039.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "22",
    "rarity": "rare"
  },
  {
    "id": "Paper 2-45",
    "paper": "Paper 2",
    "questionNumber": 45,
    "page": 40,
    "image": "gl-pages/page-040.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "990",
    "rarity": "legendary"
  },
  {
    "id": "Paper 2-46",
    "paper": "Paper 2",
    "questionNumber": 46,
    "page": 40,
    "image": "gl-pages/page-040.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "340",
    "rarity": "legendary"
  },
  {
    "id": "Paper 2-47",
    "paper": "Paper 2",
    "questionNumber": 47,
    "page": 40,
    "image": "gl-pages/page-040.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "55°",
    "rarity": "legendary"
  },
  {
    "id": "Paper 2-48",
    "paper": "Paper 2",
    "questionNumber": 48,
    "page": 41,
    "image": "gl-pages/page-041.jpg",
    "world": "💎 Crystal Cavern",
    "answer": "8.5 m²",
    "rarity": "legendary"
  },
  {
    "id": "Paper 3-16",
    "paper": "Paper 3",
    "questionNumber": 16,
    "page": 48,
    "image": "gl-pages/page-048.jpg",
    "world": "🌋 Lava Lab",
    "answer": "TOT",
    "rarity": "common"
  },
  {
    "id": "Paper 3-17",
    "paper": "Paper 3",
    "questionNumber": 17,
    "page": 49,
    "image": "gl-pages/page-049.jpg",
    "world": "🌋 Lava Lab",
    "answer": "12",
    "rarity": "common"
  },
  {
    "id": "Paper 3-22",
    "paper": "Paper 3",
    "questionNumber": 22,
    "page": 51,
    "image": "gl-pages/page-051.jpg",
    "world": "🌋 Lava Lab",
    "answer": "250 miles",
    "rarity": "common"
  },
  {
    "id": "Paper 3-30",
    "paper": "Paper 3",
    "questionNumber": 30,
    "page": 54,
    "image": "gl-pages/page-054.jpg",
    "world": "🌋 Lava Lab",
    "answer": "6.6 m",
    "rarity": "common"
  },
  {
    "id": "Paper 3-31",
    "paper": "Paper 3",
    "questionNumber": 31,
    "page": 54,
    "image": "gl-pages/page-054.jpg",
    "world": "🌋 Lava Lab",
    "answer": "1/2",
    "rarity": "common"
  },
  {
    "id": "Paper 3-36",
    "paper": "Paper 3",
    "questionNumber": 36,
    "page": 56,
    "image": "gl-pages/page-056.jpg",
    "world": "🌋 Lava Lab",
    "answer": "rectangle",
    "rarity": "rare"
  },
  {
    "id": "Paper 3-37",
    "paper": "Paper 3",
    "questionNumber": 37,
    "page": 56,
    "image": "gl-pages/page-056.jpg",
    "world": "🌋 Lava Lab",
    "answer": "210°",
    "rarity": "rare"
  },
  {
    "id": "Paper 3-38",
    "paper": "Paper 3",
    "questionNumber": 38,
    "page": 57,
    "image": "gl-pages/page-057.jpg",
    "world": "🌋 Lava Lab",
    "answer": "25800",
    "rarity": "rare"
  },
  {
    "id": "Paper 3-41",
    "paper": "Paper 3",
    "questionNumber": 41,
    "page": 58,
    "image": "gl-pages/page-058.jpg",
    "world": "🌋 Lava Lab",
    "answer": "25.5 m²",
    "rarity": "rare"
  },
  {
    "id": "Paper 3-44",
    "paper": "Paper 3",
    "questionNumber": 44,
    "page": 60,
    "image": "gl-pages/page-060.jpg",
    "world": "🌋 Lava Lab",
    "answer": "(3, 7)",
    "rarity": "rare"
  },
  {
    "id": "Paper 3-45",
    "paper": "Paper 3",
    "questionNumber": 45,
    "page": 61,
    "image": "gl-pages/page-061.jpg",
    "world": "🌋 Lava Lab",
    "answer": "£7.60",
    "rarity": "legendary"
  },
  {
    "id": "Paper 3-46",
    "paper": "Paper 3",
    "questionNumber": 46,
    "page": 61,
    "image": "gl-pages/page-061.jpg",
    "world": "🌋 Lava Lab",
    "answer": "24",
    "rarity": "legendary"
  },
  {
    "id": "Paper 3-47",
    "paper": "Paper 3",
    "questionNumber": 47,
    "page": 62,
    "image": "gl-pages/page-062.jpg",
    "world": "🌋 Lava Lab",
    "answer": "A",
    "rarity": "legendary"
  },
  {
    "id": "Paper 3-48",
    "paper": "Paper 3",
    "questionNumber": 48,
    "page": 62,
    "image": "gl-pages/page-062.jpg",
    "world": "🌋 Lava Lab",
    "answer": "5000 cm²",
    "rarity": "legendary"
  },
  {
    "id": "Paper 3-50",
    "paper": "Paper 3",
    "questionNumber": 50,
    "page": 63,
    "image": "gl-pages/page-063.jpg",
    "world": "🌋 Lava Lab",
    "answer": "1.5 cm",
    "rarity": "legendary"
  },
  {
    "id": "Paper 4-15",
    "paper": "Paper 4",
    "questionNumber": 15,
    "page": 70,
    "image": "gl-pages/page-070.jpg",
    "world": "☁️ Sky Islands",
    "answer": "4",
    "rarity": "common"
  },
  {
    "id": "Paper 4-26",
    "paper": "Paper 4",
    "questionNumber": 26,
    "page": 76,
    "image": "gl-pages/page-076.jpg",
    "world": "☁️ Sky Islands",
    "answer": "9",
    "rarity": "common"
  },
  {
    "id": "Paper 4-29",
    "paper": "Paper 4",
    "questionNumber": 29,
    "page": 77,
    "image": "gl-pages/page-077.jpg",
    "world": "☁️ Sky Islands",
    "answer": "10",
    "rarity": "common"
  },
  {
    "id": "Paper 4-31",
    "paper": "Paper 4",
    "questionNumber": 31,
    "page": 77,
    "image": "gl-pages/page-077.jpg",
    "world": "☁️ Sky Islands",
    "answer": "7",
    "rarity": "common"
  },
  {
    "id": "Paper 4-32",
    "paper": "Paper 4",
    "questionNumber": 32,
    "page": 78,
    "image": "gl-pages/page-078.jpg",
    "world": "☁️ Sky Islands",
    "answer": "1",
    "rarity": "common"
  },
  {
    "id": "Paper 4-33",
    "paper": "Paper 4",
    "questionNumber": 33,
    "page": 78,
    "image": "gl-pages/page-078.jpg",
    "world": "☁️ Sky Islands",
    "answer": "3",
    "rarity": "common"
  },
  {
    "id": "Paper 4-34",
    "paper": "Paper 4",
    "questionNumber": 34,
    "page": 78,
    "image": "gl-pages/page-078.jpg",
    "world": "☁️ Sky Islands",
    "answer": "9",
    "rarity": "common"
  },
  {
    "id": "Paper 4-35",
    "paper": "Paper 4",
    "questionNumber": 35,
    "page": 79,
    "image": "gl-pages/page-079.jpg",
    "world": "☁️ Sky Islands",
    "answer": "960g",
    "rarity": "rare"
  },
  {
    "id": "Paper 4-39",
    "paper": "Paper 4",
    "questionNumber": 39,
    "page": 80,
    "image": "gl-pages/page-080.jpg",
    "world": "☁️ Sky Islands",
    "answer": "75°",
    "rarity": "rare"
  },
  {
    "id": "Paper 4-40",
    "paper": "Paper 4",
    "questionNumber": 40,
    "page": 81,
    "image": "gl-pages/page-081.jpg",
    "world": "☁️ Sky Islands",
    "answer": "KN and NV",
    "rarity": "rare"
  },
  {
    "id": "Paper 4-45",
    "paper": "Paper 4",
    "questionNumber": 45,
    "page": 83,
    "image": "gl-pages/page-083.jpg",
    "world": "☁️ Sky Islands",
    "answer": "122°F",
    "rarity": "legendary"
  },
  {
    "id": "Paper 4-50",
    "paper": "Paper 4",
    "questionNumber": 50,
    "page": 85,
    "image": "gl-pages/page-085.jpg",
    "world": "☁️ Sky Islands",
    "answer": "10 cm²",
    "rarity": "legendary"
  },
  {
    "id": "Paper 5-1",
    "paper": "Paper 5",
    "questionNumber": 1,
    "page": 88,
    "image": "gl-pages/page-088.jpg",
    "world": "🤖 Robot Arena",
    "answer": "D",
    "rarity": "common"
  },
  {
    "id": "Paper 5-6",
    "paper": "Paper 5",
    "questionNumber": 6,
    "page": 90,
    "image": "gl-pages/page-090.jpg",
    "world": "🤖 Robot Arena",
    "answer": "2/3",
    "rarity": "common"
  },
  {
    "id": "Paper 5-7",
    "paper": "Paper 5",
    "questionNumber": 7,
    "page": 91,
    "image": "gl-pages/page-091.jpg",
    "world": "🤖 Robot Arena",
    "answer": "5",
    "rarity": "common"
  },
  {
    "id": "Paper 5-10",
    "paper": "Paper 5",
    "questionNumber": 10,
    "page": 92,
    "image": "gl-pages/page-092.jpg",
    "world": "🤖 Robot Arena",
    "answer": "0630",
    "rarity": "common"
  },
  {
    "id": "Paper 5-12",
    "paper": "Paper 5",
    "questionNumber": 12,
    "page": 93,
    "image": "gl-pages/page-093.jpg",
    "world": "🤖 Robot Arena",
    "answer": "D",
    "rarity": "common"
  },
  {
    "id": "Paper 5-14",
    "paper": "Paper 5",
    "questionNumber": 14,
    "page": 94,
    "image": "gl-pages/page-094.jpg",
    "world": "🤖 Robot Arena",
    "answer": "E",
    "rarity": "common"
  },
  {
    "id": "Paper 5-15",
    "paper": "Paper 5",
    "questionNumber": 15,
    "page": 94,
    "image": "gl-pages/page-094.jpg",
    "world": "🤖 Robot Arena",
    "answer": "2/5",
    "rarity": "common"
  },
  {
    "id": "Paper 5-18",
    "paper": "Paper 5",
    "questionNumber": 18,
    "page": 96,
    "image": "gl-pages/page-096.jpg",
    "world": "🤖 Robot Arena",
    "answer": "B and C",
    "rarity": "common"
  },
  {
    "id": "Paper 5-21",
    "paper": "Paper 5",
    "questionNumber": 21,
    "page": 97,
    "image": "gl-pages/page-097.jpg",
    "world": "🤖 Robot Arena",
    "answer": "49700",
    "rarity": "common"
  },
  {
    "id": "Paper 5-24",
    "paper": "Paper 5",
    "questionNumber": 24,
    "page": 98,
    "image": "gl-pages/page-098.jpg",
    "world": "🤖 Robot Arena",
    "answer": "C",
    "rarity": "common"
  },
  {
    "id": "Paper 5-26",
    "paper": "Paper 5",
    "questionNumber": 26,
    "page": 99,
    "image": "gl-pages/page-099.jpg",
    "world": "🤖 Robot Arena",
    "answer": "rectangle",
    "rarity": "common"
  },
  {
    "id": "Paper 5-30",
    "paper": "Paper 5",
    "questionNumber": 30,
    "page": 101,
    "image": "gl-pages/page-101.jpg",
    "world": "🤖 Robot Arena",
    "answer": "150 m",
    "rarity": "common"
  },
  {
    "id": "Paper 5-34",
    "paper": "Paper 5",
    "questionNumber": 34,
    "page": 103,
    "image": "gl-pages/page-103.jpg",
    "world": "🤖 Robot Arena",
    "answer": "20",
    "rarity": "common"
  },
  {
    "id": "Paper 5-35",
    "paper": "Paper 5",
    "questionNumber": 35,
    "page": 103,
    "image": "gl-pages/page-103.jpg",
    "world": "🤖 Robot Arena",
    "answer": "36p",
    "rarity": "rare"
  },
  {
    "id": "Paper 5-36",
    "paper": "Paper 5",
    "questionNumber": 36,
    "page": 104,
    "image": "gl-pages/page-104.jpg",
    "world": "🤖 Robot Arena",
    "answer": "10p and 20p",
    "rarity": "rare"
  },
  {
    "id": "Paper 5-37",
    "paper": "Paper 5",
    "questionNumber": 37,
    "page": 104,
    "image": "gl-pages/page-104.jpg",
    "world": "🤖 Robot Arena",
    "answer": "80",
    "rarity": "rare"
  },
  {
    "id": "Paper 5-38",
    "paper": "Paper 5",
    "questionNumber": 38,
    "page": 105,
    "image": "gl-pages/page-105.jpg",
    "world": "🤖 Robot Arena",
    "answer": "a right-angled triangle",
    "rarity": "rare"
  },
  {
    "id": "Paper 5-40",
    "paper": "Paper 5",
    "questionNumber": 40,
    "page": 105,
    "image": "gl-pages/page-105.jpg",
    "world": "🤖 Robot Arena",
    "answer": "£200",
    "rarity": "rare"
  },
  {
    "id": "Paper 5-41",
    "paper": "Paper 5",
    "questionNumber": 41,
    "page": 106,
    "image": "gl-pages/page-106.jpg",
    "world": "🤖 Robot Arena",
    "answer": "160 cm",
    "rarity": "rare"
  },
  {
    "id": "Paper 5-43",
    "paper": "Paper 5",
    "questionNumber": 43,
    "page": 107,
    "image": "gl-pages/page-107.jpg",
    "world": "🤖 Robot Arena",
    "answer": "E",
    "rarity": "rare"
  },
  {
    "id": "Paper 5-44",
    "paper": "Paper 5",
    "questionNumber": 44,
    "page": 107,
    "image": "gl-pages/page-107.jpg",
    "world": "🤖 Robot Arena",
    "answer": "C",
    "rarity": "rare"
  },
  {
    "id": "Paper 5-46",
    "paper": "Paper 5",
    "questionNumber": 46,
    "page": 108,
    "image": "gl-pages/page-108.jpg",
    "world": "🤖 Robot Arena",
    "answer": "(6, 6)",
    "rarity": "legendary"
  },
  {
    "id": "Paper 5-48",
    "paper": "Paper 5",
    "questionNumber": 48,
    "page": 109,
    "image": "gl-pages/page-109.jpg",
    "world": "🤖 Robot Arena",
    "answer": "e = h",
    "rarity": "legendary"
  },
  {
    "id": "Paper 5-50",
    "paper": "Paper 5",
    "questionNumber": 50,
    "page": 109,
    "image": "gl-pages/page-109.jpg",
    "world": "🤖 Robot Arena",
    "answer": "£18",
    "rarity": "legendary"
  },
  {
    "id": "Paper 6-1",
    "paper": "Paper 6",
    "questionNumber": 1,
    "page": 112,
    "image": "gl-pages/page-112.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "4",
    "rarity": "common"
  },
  {
    "id": "Paper 6-2",
    "paper": "Paper 6",
    "questionNumber": 2,
    "page": 112,
    "image": "gl-pages/page-112.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "1/4",
    "rarity": "common"
  },
  {
    "id": "Paper 6-3",
    "paper": "Paper 6",
    "questionNumber": 3,
    "page": 113,
    "image": "gl-pages/page-113.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "B",
    "rarity": "common"
  },
  {
    "id": "Paper 6-4",
    "paper": "Paper 6",
    "questionNumber": 4,
    "page": 113,
    "image": "gl-pages/page-113.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "35",
    "rarity": "common"
  },
  {
    "id": "Paper 6-5",
    "paper": "Paper 6",
    "questionNumber": 5,
    "page": 114,
    "image": "gl-pages/page-114.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "B",
    "rarity": "common"
  },
  {
    "id": "Paper 6-9",
    "paper": "Paper 6",
    "questionNumber": 9,
    "page": 116,
    "image": "gl-pages/page-116.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "D",
    "rarity": "common"
  },
  {
    "id": "Paper 6-11",
    "paper": "Paper 6",
    "questionNumber": 11,
    "page": 117,
    "image": "gl-pages/page-117.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "(20, 10)",
    "rarity": "common"
  },
  {
    "id": "Paper 6-13",
    "paper": "Paper 6",
    "questionNumber": 13,
    "page": 118,
    "image": "gl-pages/page-118.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "E",
    "rarity": "common"
  },
  {
    "id": "Paper 6-17",
    "paper": "Paper 6",
    "questionNumber": 17,
    "page": 119,
    "image": "gl-pages/page-119.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "square centimetres",
    "rarity": "common"
  },
  {
    "id": "Paper 6-18",
    "paper": "Paper 6",
    "questionNumber": 18,
    "page": 119,
    "image": "gl-pages/page-119.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "8",
    "rarity": "common"
  },
  {
    "id": "Paper 6-19",
    "paper": "Paper 6",
    "questionNumber": 19,
    "page": 120,
    "image": "gl-pages/page-120.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "A",
    "rarity": "common"
  },
  {
    "id": "Paper 6-20",
    "paper": "Paper 6",
    "questionNumber": 20,
    "page": 121,
    "image": "gl-pages/page-121.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "C",
    "rarity": "common"
  },
  {
    "id": "Paper 6-22",
    "paper": "Paper 6",
    "questionNumber": 22,
    "page": 122,
    "image": "gl-pages/page-122.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "2a + 2b",
    "rarity": "common"
  },
  {
    "id": "Paper 6-26",
    "paper": "Paper 6",
    "questionNumber": 26,
    "page": 123,
    "image": "gl-pages/page-123.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "30p",
    "rarity": "common"
  },
  {
    "id": "Paper 6-29",
    "paper": "Paper 6",
    "questionNumber": 29,
    "page": 124,
    "image": "gl-pages/page-124.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "16",
    "rarity": "common"
  },
  {
    "id": "Paper 6-30",
    "paper": "Paper 6",
    "questionNumber": 30,
    "page": 125,
    "image": "gl-pages/page-125.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "-3",
    "rarity": "common"
  },
  {
    "id": "Paper 6-31",
    "paper": "Paper 6",
    "questionNumber": 31,
    "page": 125,
    "image": "gl-pages/page-125.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "24",
    "rarity": "common"
  },
  {
    "id": "Paper 6-32",
    "paper": "Paper 6",
    "questionNumber": 32,
    "page": 125,
    "image": "gl-pages/page-125.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "20.8",
    "rarity": "common"
  },
  {
    "id": "Paper 6-33",
    "paper": "Paper 6",
    "questionNumber": 33,
    "page": 125,
    "image": "gl-pages/page-125.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "2014",
    "rarity": "common"
  },
  {
    "id": "Paper 6-35",
    "paper": "Paper 6",
    "questionNumber": 35,
    "page": 126,
    "image": "gl-pages/page-126.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "4 km",
    "rarity": "rare"
  },
  {
    "id": "Paper 6-36",
    "paper": "Paper 6",
    "questionNumber": 36,
    "page": 127,
    "image": "gl-pages/page-127.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "Friday",
    "rarity": "rare"
  },
  {
    "id": "Paper 6-38",
    "paper": "Paper 6",
    "questionNumber": 38,
    "page": 127,
    "image": "gl-pages/page-127.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "26",
    "rarity": "rare"
  },
  {
    "id": "Paper 6-40",
    "paper": "Paper 6",
    "questionNumber": 40,
    "page": 128,
    "image": "gl-pages/page-128.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "5",
    "rarity": "rare"
  },
  {
    "id": "Paper 6-42",
    "paper": "Paper 6",
    "questionNumber": 42,
    "page": 129,
    "image": "gl-pages/page-129.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "3.01 and 2.99",
    "rarity": "rare"
  },
  {
    "id": "Paper 6-43",
    "paper": "Paper 6",
    "questionNumber": 43,
    "page": 129,
    "image": "gl-pages/page-129.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "8",
    "rarity": "rare"
  },
  {
    "id": "Paper 6-44",
    "paper": "Paper 6",
    "questionNumber": 44,
    "page": 129,
    "image": "gl-pages/page-129.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "170000",
    "rarity": "rare"
  },
  {
    "id": "Paper 6-45",
    "paper": "Paper 6",
    "questionNumber": 45,
    "page": 130,
    "image": "gl-pages/page-130.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "56 m",
    "rarity": "legendary"
  },
  {
    "id": "Paper 6-47",
    "paper": "Paper 6",
    "questionNumber": 47,
    "page": 131,
    "image": "gl-pages/page-131.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "40%",
    "rarity": "legendary"
  },
  {
    "id": "Paper 6-49",
    "paper": "Paper 6",
    "questionNumber": 49,
    "page": 132,
    "image": "gl-pages/page-132.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "150°",
    "rarity": "legendary"
  },
  {
    "id": "Paper 6-50",
    "paper": "Paper 6",
    "questionNumber": 50,
    "page": 132,
    "image": "gl-pages/page-132.jpg",
    "world": "🏴‍☠️ Pirate Port",
    "answer": "£9",
    "rarity": "legendary"
  },
  {
    "id": "Paper 7-6",
    "paper": "Paper 7",
    "questionNumber": 6,
    "page": 137,
    "image": "gl-pages/page-137.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "18.25 litres",
    "rarity": "common"
  },
  {
    "id": "Paper 7-13",
    "paper": "Paper 7",
    "questionNumber": 13,
    "page": 140,
    "image": "gl-pages/page-140.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "5",
    "rarity": "common"
  },
  {
    "id": "Paper 7-16",
    "paper": "Paper 7",
    "questionNumber": 16,
    "page": 141,
    "image": "gl-pages/page-141.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "6",
    "rarity": "common"
  },
  {
    "id": "Paper 7-17",
    "paper": "Paper 7",
    "questionNumber": 17,
    "page": 142,
    "image": "gl-pages/page-142.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "21",
    "rarity": "common"
  },
  {
    "id": "Paper 7-20",
    "paper": "Paper 7",
    "questionNumber": 20,
    "page": 143,
    "image": "gl-pages/page-143.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "50",
    "rarity": "common"
  },
  {
    "id": "Paper 7-24",
    "paper": "Paper 7",
    "questionNumber": 24,
    "page": 145,
    "image": "gl-pages/page-145.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "7",
    "rarity": "common"
  },
  {
    "id": "Paper 7-25",
    "paper": "Paper 7",
    "questionNumber": 25,
    "page": 145,
    "image": "gl-pages/page-145.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "Hexagon",
    "rarity": "common"
  },
  {
    "id": "Paper 7-27",
    "paper": "Paper 7",
    "questionNumber": 27,
    "page": 146,
    "image": "gl-pages/page-146.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "1",
    "rarity": "common"
  },
  {
    "id": "Paper 7-31",
    "paper": "Paper 7",
    "questionNumber": 31,
    "page": 147,
    "image": "gl-pages/page-147.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "C",
    "rarity": "common"
  },
  {
    "id": "Paper 7-37",
    "paper": "Paper 7",
    "questionNumber": 37,
    "page": 150,
    "image": "gl-pages/page-150.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "2 pentagons",
    "rarity": "rare"
  },
  {
    "id": "Paper 7-39",
    "paper": "Paper 7",
    "questionNumber": 39,
    "page": 151,
    "image": "gl-pages/page-151.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "kites",
    "rarity": "rare"
  },
  {
    "id": "Paper 7-41",
    "paper": "Paper 7",
    "questionNumber": 41,
    "page": 152,
    "image": "gl-pages/page-152.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "B",
    "rarity": "rare"
  },
  {
    "id": "Paper 7-42",
    "paper": "Paper 7",
    "questionNumber": 42,
    "page": 152,
    "image": "gl-pages/page-152.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "2 hrs 18 mins",
    "rarity": "rare"
  },
  {
    "id": "Paper 7-44",
    "paper": "Paper 7",
    "questionNumber": 44,
    "page": 153,
    "image": "gl-pages/page-153.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "D",
    "rarity": "rare"
  },
  {
    "id": "Paper 7-45",
    "paper": "Paper 7",
    "questionNumber": 45,
    "page": 154,
    "image": "gl-pages/page-154.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "9",
    "rarity": "legendary"
  },
  {
    "id": "Paper 7-46",
    "paper": "Paper 7",
    "questionNumber": 46,
    "page": 154,
    "image": "gl-pages/page-154.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "28 m²",
    "rarity": "legendary"
  },
  {
    "id": "Paper 7-47",
    "paper": "Paper 7",
    "questionNumber": 47,
    "page": 154,
    "image": "gl-pages/page-154.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "6 tins",
    "rarity": "legendary"
  },
  {
    "id": "Paper 7-48",
    "paper": "Paper 7",
    "questionNumber": 48,
    "page": 155,
    "image": "gl-pages/page-155.jpg",
    "world": "🪐 Cosmic Castle",
    "answer": "15m",
    "rarity": "legendary"
  },
  {
    "id": "Paper 8-3",
    "paper": "Paper 8",
    "questionNumber": 3,
    "page": 160,
    "image": "gl-pages/page-160.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "7 minutes",
    "rarity": "common"
  },
  {
    "id": "Paper 8-4",
    "paper": "Paper 8",
    "questionNumber": 4,
    "page": 160,
    "image": "gl-pages/page-160.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "36",
    "rarity": "common"
  },
  {
    "id": "Paper 8-6",
    "paper": "Paper 8",
    "questionNumber": 6,
    "page": 161,
    "image": "gl-pages/page-161.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "£29.90",
    "rarity": "common"
  },
  {
    "id": "Paper 8-12",
    "paper": "Paper 8",
    "questionNumber": 12,
    "page": 164,
    "image": "gl-pages/page-164.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "45g",
    "rarity": "common"
  },
  {
    "id": "Paper 8-13",
    "paper": "Paper 8",
    "questionNumber": 13,
    "page": 165,
    "image": "gl-pages/page-165.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "54cm",
    "rarity": "common"
  },
  {
    "id": "Paper 8-15",
    "paper": "Paper 8",
    "questionNumber": 15,
    "page": 166,
    "image": "gl-pages/page-166.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "31",
    "rarity": "common"
  },
  {
    "id": "Paper 8-16",
    "paper": "Paper 8",
    "questionNumber": 16,
    "page": 167,
    "image": "gl-pages/page-167.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "36",
    "rarity": "common"
  },
  {
    "id": "Paper 8-17",
    "paper": "Paper 8",
    "questionNumber": 17,
    "page": 167,
    "image": "gl-pages/page-167.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "1 and 6",
    "rarity": "common"
  },
  {
    "id": "Paper 8-20",
    "paper": "Paper 8",
    "questionNumber": 20,
    "page": 168,
    "image": "gl-pages/page-168.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "C",
    "rarity": "common"
  },
  {
    "id": "Paper 8-24",
    "paper": "Paper 8",
    "questionNumber": 24,
    "page": 170,
    "image": "gl-pages/page-170.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "parallelogram",
    "rarity": "common"
  },
  {
    "id": "Paper 8-25",
    "paper": "Paper 8",
    "questionNumber": 25,
    "page": 171,
    "image": "gl-pages/page-171.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "B",
    "rarity": "common"
  },
  {
    "id": "Paper 8-29",
    "paper": "Paper 8",
    "questionNumber": 29,
    "page": 173,
    "image": "gl-pages/page-173.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "150°",
    "rarity": "common"
  },
  {
    "id": "Paper 8-34",
    "paper": "Paper 8",
    "questionNumber": 34,
    "page": 175,
    "image": "gl-pages/page-175.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "(1, 3) and (4, 2)",
    "rarity": "common"
  },
  {
    "id": "Paper 8-36",
    "paper": "Paper 8",
    "questionNumber": 36,
    "page": 176,
    "image": "gl-pages/page-176.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "1.42 m²",
    "rarity": "rare"
  },
  {
    "id": "Paper 8-39",
    "paper": "Paper 8",
    "questionNumber": 39,
    "page": 176,
    "image": "gl-pages/page-176.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "9",
    "rarity": "rare"
  },
  {
    "id": "Paper 8-44",
    "paper": "Paper 8",
    "questionNumber": 44,
    "page": 178,
    "image": "gl-pages/page-178.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "£18.00",
    "rarity": "rare"
  },
  {
    "id": "Paper 8-46",
    "paper": "Paper 8",
    "questionNumber": 46,
    "page": 179,
    "image": "gl-pages/page-179.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "8 and 15",
    "rarity": "legendary"
  },
  {
    "id": "Paper 8-47",
    "paper": "Paper 8",
    "questionNumber": 47,
    "page": 179,
    "image": "gl-pages/page-179.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "D",
    "rarity": "legendary"
  },
  {
    "id": "Paper 8-48",
    "paper": "Paper 8",
    "questionNumber": 48,
    "page": 180,
    "image": "gl-pages/page-180.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "4 panels and 5 posts",
    "rarity": "legendary"
  },
  {
    "id": "Paper 8-50",
    "paper": "Paper 8",
    "questionNumber": 50,
    "page": 180,
    "image": "gl-pages/page-180.jpg",
    "world": "🌴 Jungle Dash",
    "answer": "17hrs, 14mins, 24secs",
    "rarity": "legendary"
  },
  {
    "id": "Paper 9-4",
    "paper": "Paper 9",
    "questionNumber": 4,
    "page": 184,
    "image": "gl-pages/page-184.jpg",
    "world": "👑 Boss Tower",
    "answer": "1/25",
    "rarity": "common"
  },
  {
    "id": "Paper 9-6",
    "paper": "Paper 9",
    "questionNumber": 6,
    "page": 184,
    "image": "gl-pages/page-184.jpg",
    "world": "👑 Boss Tower",
    "answer": "3",
    "rarity": "common"
  },
  {
    "id": "Paper 9-11",
    "paper": "Paper 9",
    "questionNumber": 11,
    "page": 186,
    "image": "gl-pages/page-186.jpg",
    "world": "👑 Boss Tower",
    "answer": "Dylan",
    "rarity": "common"
  },
  {
    "id": "Paper 9-12",
    "paper": "Paper 9",
    "questionNumber": 12,
    "page": 187,
    "image": "gl-pages/page-187.jpg",
    "world": "👑 Boss Tower",
    "answer": "57.54",
    "rarity": "common"
  },
  {
    "id": "Paper 9-14",
    "paper": "Paper 9",
    "questionNumber": 14,
    "page": 187,
    "image": "gl-pages/page-187.jpg",
    "world": "👑 Boss Tower",
    "answer": "C",
    "rarity": "common"
  },
  {
    "id": "Paper 9-19",
    "paper": "Paper 9",
    "questionNumber": 19,
    "page": 189,
    "image": "gl-pages/page-189.jpg",
    "world": "👑 Boss Tower",
    "answer": "£0.80",
    "rarity": "common"
  },
  {
    "id": "Paper 9-20",
    "paper": "Paper 9",
    "questionNumber": 20,
    "page": 189,
    "image": "gl-pages/page-189.jpg",
    "world": "👑 Boss Tower",
    "answer": "B",
    "rarity": "common"
  },
  {
    "id": "Paper 9-23",
    "paper": "Paper 9",
    "questionNumber": 23,
    "page": 190,
    "image": "gl-pages/page-190.jpg",
    "world": "👑 Boss Tower",
    "answer": "£12.05",
    "rarity": "common"
  },
  {
    "id": "Paper 9-24",
    "paper": "Paper 9",
    "questionNumber": 24,
    "page": 191,
    "image": "gl-pages/page-191.jpg",
    "world": "👑 Boss Tower",
    "answer": "80",
    "rarity": "common"
  },
  {
    "id": "Paper 9-28",
    "paper": "Paper 9",
    "questionNumber": 28,
    "page": 192,
    "image": "gl-pages/page-192.jpg",
    "world": "👑 Boss Tower",
    "answer": "1.63 m",
    "rarity": "common"
  },
  {
    "id": "Paper 9-31",
    "paper": "Paper 9",
    "questionNumber": 31,
    "page": 193,
    "image": "gl-pages/page-193.jpg",
    "world": "👑 Boss Tower",
    "answer": "B",
    "rarity": "common"
  },
  {
    "id": "Paper 9-32",
    "paper": "Paper 9",
    "questionNumber": 32,
    "page": 194,
    "image": "gl-pages/page-194.jpg",
    "world": "👑 Boss Tower",
    "answer": "25.5 m",
    "rarity": "common"
  },
  {
    "id": "Paper 9-33",
    "paper": "Paper 9",
    "questionNumber": 33,
    "page": 194,
    "image": "gl-pages/page-194.jpg",
    "world": "👑 Boss Tower",
    "answer": "11:49",
    "rarity": "common"
  },
  {
    "id": "Paper 9-34",
    "paper": "Paper 9",
    "questionNumber": 34,
    "page": 195,
    "image": "gl-pages/page-195.jpg",
    "world": "👑 Boss Tower",
    "answer": "£0.50",
    "rarity": "common"
  },
  {
    "id": "Paper 9-35",
    "paper": "Paper 9",
    "questionNumber": 35,
    "page": 195,
    "image": "gl-pages/page-195.jpg",
    "world": "👑 Boss Tower",
    "answer": "28 m",
    "rarity": "rare"
  },
  {
    "id": "Paper 9-36",
    "paper": "Paper 9",
    "questionNumber": 36,
    "page": 196,
    "image": "gl-pages/page-196.jpg",
    "world": "👑 Boss Tower",
    "answer": "42",
    "rarity": "rare"
  },
  {
    "id": "Paper 9-37",
    "paper": "Paper 9",
    "questionNumber": 37,
    "page": 196,
    "image": "gl-pages/page-196.jpg",
    "world": "👑 Boss Tower",
    "answer": "square",
    "rarity": "rare"
  },
  {
    "id": "Paper 9-38",
    "paper": "Paper 9",
    "questionNumber": 38,
    "page": 197,
    "image": "gl-pages/page-197.jpg",
    "world": "👑 Boss Tower",
    "answer": "144",
    "rarity": "rare"
  },
  {
    "id": "Paper 9-39",
    "paper": "Paper 9",
    "questionNumber": 39,
    "page": 197,
    "image": "gl-pages/page-197.jpg",
    "world": "👑 Boss Tower",
    "answer": "9.9 minutes",
    "rarity": "rare"
  },
  {
    "id": "Paper 9-40",
    "paper": "Paper 9",
    "questionNumber": 40,
    "page": 198,
    "image": "gl-pages/page-198.jpg",
    "world": "👑 Boss Tower",
    "answer": "69 m, 63/100 km, 0.67 km",
    "rarity": "rare"
  },
  {
    "id": "Paper 9-41",
    "paper": "Paper 9",
    "questionNumber": 41,
    "page": 198,
    "image": "gl-pages/page-198.jpg",
    "world": "👑 Boss Tower",
    "answer": "A",
    "rarity": "rare"
  },
  {
    "id": "Paper 9-45",
    "paper": "Paper 9",
    "questionNumber": 45,
    "page": 200,
    "image": "gl-pages/page-200.jpg",
    "world": "👑 Boss Tower",
    "answer": "54°",
    "rarity": "legendary"
  },
  {
    "id": "Paper 9-47",
    "paper": "Paper 9",
    "questionNumber": 47,
    "page": 201,
    "image": "gl-pages/page-201.jpg",
    "world": "👑 Boss Tower",
    "answer": "26",
    "rarity": "legendary"
  },
  {
    "id": "Paper 9-48",
    "paper": "Paper 9",
    "questionNumber": 48,
    "page": 201,
    "image": "gl-pages/page-201.jpg",
    "world": "👑 Boss Tower",
    "answer": "1.95, 2.05",
    "rarity": "legendary"
  }
];
window.SELECTED_REFS = {
  "Paper 1": [
    24,
    32,
    33,
    36,
    39,
    41,
    43,
    44,
    46,
    47,
    48,
    50
  ],
  "Paper 2": [
    21,
    22,
    26,
    27,
    31,
    35,
    39,
    42,
    44,
    45,
    46,
    47,
    48
  ],
  "Paper 3": [
    16,
    17,
    22,
    30,
    31,
    36,
    37,
    38,
    41,
    44,
    45,
    46,
    47,
    48,
    50
  ],
  "Paper 4": [
    15,
    26,
    29,
    31,
    32,
    33,
    34,
    35,
    39,
    40,
    45,
    50
  ],
  "Paper 5": [
    1,
    6,
    7,
    10,
    12,
    14,
    15,
    18,
    21,
    24,
    26,
    30,
    34,
    35,
    36,
    37,
    38,
    40,
    41,
    43,
    44,
    46,
    48,
    50
  ],
  "Paper 6": [
    1,
    2,
    3,
    4,
    5,
    9,
    11,
    13,
    17,
    18,
    19,
    20,
    22,
    26,
    29,
    30,
    31,
    32,
    33,
    35,
    36,
    38,
    40,
    42,
    43,
    44,
    45,
    47,
    49,
    50
  ],
  "Paper 7": [
    6,
    13,
    16,
    17,
    20,
    24,
    25,
    27,
    31,
    37,
    39,
    41,
    42,
    44,
    45,
    46,
    47,
    48
  ],
  "Paper 8": [
    3,
    4,
    6,
    12,
    13,
    15,
    16,
    17,
    20,
    24,
    25,
    29,
    34,
    36,
    39,
    44,
    46,
    47,
    48,
    50
  ],
  "Paper 9": [
    4,
    6,
    11,
    12,
    14,
    19,
    20,
    23,
    24,
    28,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    45,
    47,
    48
  ]
};
